bptlab/chor-js

lib/util/BandUtil.js
test/spec/ChoreoModelerSpec.js

Fixes an error where diBand.bound object was accidentally overridden. This reenables the import functionality. Fixes #43

Fix an error which disabled the export button

---

lib/features/behavior/CreateChoreoTaskBehavior.js
lib/features/cmd/CreateParticipantBandHandler.js
lib/features/cmd/MoveParticipantBandHandler.js
lib/import/ChoreoImporter.js
lib/import/ChoreoTreeWalker.js
lib/util/BandUtil.js
package.json
test/resources/example.bpmn
test/resources/subChoreographies.bpmn
test/resources/tasksWithLoopType.bpmn
test/resources/tasksWithMultiplicities.bpmn
test/spec/ChoreoModelerSpec.js
test/spec/diagram.bpmn

Change participantRefs to participantRef

---

lib/draw/ChoreoRenderer.js
lib/features/modeling/ChoreoElementFactory.js
lib/features/modeling/behavior/CreateChoreoTaskBehavior.js
lib/features/palette/PaletteProvider.js
lib/import/ChoreoImporter.js
test/spec/ChoreoModelerSpec.js

This PR introduces various adjustments to the handling of sub choreographies such as correct markers, the ability to create them initially and more.

Various sub-choreography adjustments

---

lib/features/rules/ChoreoRules.js
package.json

Fix sequence flow after event-based gateway

---

lib/Modeler.js
lib/features/keyboard/ChoreoKeyboardBindings.js
lib/features/keyboard/index.js

Resolves #47 
Participant bands are now swappable using the arrow keys, and removable via DEL.

Keyboard bindings for participant bands

---

lib/features/context-pad/ContextPadProvider.js

Quick fix for a bug introduced in #79.

Fix replace menu appearing on all elements

---

lib/features/context-pad/ContextPadProvider.js
lib/features/popup-menu/ReplaceMenuProvider.js
lib/features/popup-menu/index.js

Resolves #84 
The PR adds replace menus for events and gateways.

Replace events, gateways

---

.eslintrc
index.js
lib/Modeler.js
lib/NavigatedViewer.js
lib/Viewer.js
lib/draw/ChoreoRenderer.js
lib/import/ChoreoImporter.js
lib/import/ChoreoTreeWalker.js
lib/import/ImportHandler.js
lib/util/MessageUtil.js
package.json

Resolves #83 
This PR allows users to only use the viewer capabilities of chor-js.

Split Viewer/Modeler

---

lib/import/ChoreoTreeWalker.js

Fix an error where diagrams without any elements were not imported.

---

lib/features/modeling/cmd/AddMessageHandler.js

Thus, non-initiating messages were not shown

Fix an Error that caused incorrect message flows to be generated

---

lib/features/rules/ChoreoRules.js

Disallow placement of elements inside collapsed sub-choreos

---

README.md
package.json

Removes babel-preset-es2015 dependency. Also closes #103

Remove babel

---

lib/features/context-pad/ContextPadProvider.js
lib/features/modeling/ChoreoModeling.js
lib/features/modeling/cmd/MakeInitiatingParticipantBandHandler.js
lib/features/modeling/cmd/SwapInitiatingParticipantHandler.js
lib/features/rules/ChoreoRules.js
lib/util/BandUtil.js
lib/util/MessageUtil.js

Resolves #112 
Resolves #108 
- fix a bug that would produce invalid business models when making a band initiating that did not previously have a message attached
- allow swapping for the initiating participant as well

Fix swap initiating participant feature

---

lib/features/modeling/ChoreoModeling.js
lib/features/modeling/behavior/CreateChoreoTaskBehavior.js
lib/features/modeling/cmd/ChoreoAppendShapeHandler.js
lib/util/DiagramWalkerUtil.js

Add prediction for participants of an appended ChoreoActivity. 
Resolves #87

Participant prediction #87

---

.npmignore
README.md
docs/tutorial.md
package.json

Change references and stuff for the move to bptlab.

Move repository to bptlab

---

README.md
lib/Modeler.js
lib/Viewer.js
lib/import/visitors/InitialRenderVisitor.js

Testing the Travis integration.

Fix travis

---

lib/features/utils/ChoreoUtil.js

Fix removal of the first diagram

---

lib/import/ChoreoTreeWalker.js
lib/import/visitors/InitialRenderVisitor.js

Fix import of message flows with no message attached

---

lib/features/modeling/ChoreoModeling.js

Fixes a bug where bands would be separated from their activities by the space tool.

Fix make space tool

---

lib/features/keyboard-move-selection/ChoreoMoveSelection.js

Allows moving selected shapes if bands and activity are selected together. Fixes #106

Allow moving selected shapes

---

lib/core/index.js
lib/import/ChoreoTreeWalker.js
lib/import/ImportHandler.js
lib/import/index.js
lib/import/visitors/InitialRenderVisitor.js
lib/import/visitors/RestoreFromCacheVisitor.js
lib/import/visitors/index.js
package.json

This PR refactors the import visitors to be modules so they can be overridden in projects using chor-js.

Modularize import visitors

---

lib/features/copy-paste/ChoreoCopyPaste.js
lib/util/DiagramWalkerUtil.js

Make copy paste extendable for active-chor-js.

Extendable copypaste
